- name: CachyOS post-configuration
  hosts: localhost
  roles:
    - tmux
    - lazyvim
  tasks:
    - name: Install additional packages
      community.general.pacman:
        name:
          - firefox
          - 7zip
          - virtualbox
          - virtualbox-guest-iso
          - bitwarden
          - nextcloud-client
      become: true
    - name: Set hyprland keyboard layout
      ansible.builtin.blockinfile:
        path: "~/.config/hypr/config/inputs.lua"
        marker: "-- {mark} ANSIBLE kb_layout"
        insertafter: 'input = {'
        block: |
          kb_layout = "se",
    - name: Set greeter keyboard layout
      ansible.builtin.blockinfile:
        path: "/var/lib/noctalia-greeter/greeter.toml"
        marker: "# {mark} ANSIBLE keyboard layout"
        insertafter: EOF
        block: |
          [keyboard]
          layout = "se"
      become: true
    - name: Additional home folders
      ansible.builtin.file:
        name: "~/{{ item }}"
        state: "directory"
      loop:
        - "repos"
        - "tmp"
        - "mnt"
